{
 "title": "Netdata-Grafana-Dashboard",
 "time": { "from": "2025-12-11T07:29:10.580Z", "to": "2025-12-11T13:29:10.580Z" },
 "panels": [
  {
   "title": "Total Memory ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average)\r\n"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{dimension=\"free\"}\r\n"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{dimension=\"used\"}\r\n\r\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "netdata_system_net_kilobits_persec_average{dimension=\"received\"}\r\n",
     "legendFormat": "received rate"
    },
    {
     "expr": "netdata_system_net_kilobits_persec_average{dimension=\"sent\"}\r\n",
     "legendFormat": "sent rate"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average{dimension=\"softirq\"}\r\n\r\n\r\n\r\n",
     "legendFormat": "softirq"
    },
    {
     "expr": "netdata_system_cpu_percentage_average{dimension=\"user\"}",
     "legendFormat": "user"
    },
    {
     "expr": "netdata_system_cpu_percentage_average{dimension=\"system\"}",
     "legendFormat": "system"
    },
    {
     "expr": "netdata_system_cpu_percentage_average{dimension=\"iowait\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "100 - netdata_system_cpu_percentage_average{dimension=\"idle\"}\r\n",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "netdata_system_io_KiB_persec_average{dimension=\"reads\"}\r\n",
     "legendFormat": "read KiB"
    },
    {
     "expr": "netdata_system_io_KiB_persec_average{dimension=\"writes\"}",
     "legendFormat": "writes KiB"
    }
   ]
  },
  {
   "title": "Processes Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_processes_processes_average{dimension=\"running\"}\r\n\r\n"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average\r\n"
    }
   ]
  },
  {
   "title": "Processes Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_processes_processes_average{dimension=\"blocked\"}\r\n"
    }
   ]
  }
 ]
}